# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    exclude: testing/baselines
  - id: end-of-file-fixer
    exclude: testing/baselines
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
    - id: ruff
      args: [--fix]
      exclude: zeekpkg/tarfile_fallback.py
    - id: ruff-format
      exclude: zeekpkg/tarfile_fallback.py
